version: 2
jobs:
  build:
    docker:
      - image: cimg/base:current
    working_directory: /go/src/github.com/gliderlabs/registrator
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: make circleci
      - run:
          name: Build
          command: make build
